### ISSUE TITLE
Unable to load the model Anuvaad

### ISSUE THREAD

**Issue by priyaradhakrishnan0** [notAI-tech/Anuvaad#1]
>>> anu = anuvaad("english-malayalam")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
>>> anuvaad
<module 'anuvaad.anuvaad' from '/opt/conda/envs/translate/lib/python3.6/site-packages/anuvaad/anuvaad.py'>
>>> anu = anuvaad("english-telugu")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable

**Comment by bedapudi6788** [comment]
```python
from anuvaad import Anuvaad
anu = Anuvaad("english-telugu")
````
is the correct usage.

**Comment by bedapudi6788** [comment]
@priyaradhakrishnan0 I am closing this issue. Feel free to re-open if not solved.
