### ISSUE TITLE
Adding Anuvaad to indic.page

### ISSUE THREAD

**Issue by bnkamalesh** [notAI-tech/Anuvaad#3]
I've created an MR to add your repository to [indic.page](https://indic.page). [https://github.com/knadh/indic.page/pull/12](https://github.com/knadh/indic.page/pull/12) is the pull request. Please do let me know if there's any concern

**Comment by bedapudi6788** [comment]
@bnkamalesh thank you! I was not ware of this repo. It looks really useful!
