### ISSUE TITLE
AttributeError: module 'tensorflow._api.v1.initializers' has no attribute 'TruncatedNormal'

### ISSUE THREAD

**Issue by sri1905** [notAI-tech/Anuvaad#4]
I am getting that AttributeError when I try on my local terminal. Could you give me requirements.txt ?
Thank you

![Screenshot from 2020-11-27 18-17-53](https://user-images.githubusercontent.com/14858682/100451142-e81bb380-30dc-11eb-8631-08439240a01e.png)

**Comment by bedapudi6788** [comment]
@sri1905 did you change any code or is this the module installed by pip install --upgrade anuvaad? from_tf=True should not have been used. The provided weights are pytorch weights.

**Comment by sri1905** [comment]
Its the module installed by `pip install --upgrade anuvaad`, I am using tensorflow 1.15 and python 3.6.9. Nothing else modified.

**Comment by bedapudi6788** [comment]
https://github.com/notAI-tech/Anuvaad/blob/4c024309bedbe1223c27bbc6bb45f896e86890d9/setup.py#L24 the requirements are defined here.

**Comment by bedapudi6788** [comment]
@sri1905 https://colab.research.google.com/drive/1ixxaJK9_4qobHckUxTQw3yV95cCbqqLS?usp=sharing here is a colab showing the expected logs when anuvaad is correctly setup.

**Comment by sri1905** [comment]
I have added the suggested requirements to a .txt file and ran `pip install -r ` on it. Strangly I get the old OSError which asks me to set the "from_tf=True". Also, it works on colab but fails to work in my terminal or jupyter notebook.
![Screenshot from 2020-11-28 12-40-11](https://user-images.githubusercontent.com/14858682/100496088-3d0c0800-3177-11eb-92e3-63ecdb6c6975.png)

**Comment by bedapudi6788** [comment]
https://github.com/notAI-tech/Anuvaad/issues/2#issuecomment-733251931 did you do this?

**Comment by sri1905** [comment]
Now I did and the pythorch_model.bin is loading. Thank you soo much !
